Sonata_WMS_finale/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('product_tracking.urls')),
    path('admin/', admin.site.urls),


]

product_tracking/urls.py
# urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import user_logout, item_list

app_name = 'product_tracking'
urlpatterns = [
    path('', views.custom_login, name='login_view'),
    path('index/', views.index_view, name='index'),
    path('login/', views.custom_login, name='login_view'),
    path('logout/', user_logout, name='logout'),
    path('production_order/', views.production_order, name='production_order'),
    path('label_printing/', views.label_printing, name='label_printing'),
    path('label_reprinting/', views.label_reprinting, name='label_reprinting'),
    path('stock_verification/', views.stock_verification, name='stock_verification'),
    path('stock_approval/', views.stock_approval, name='stock_approval'),
    path('add_user/', views.add_user, name='add_user'),
    path('add_item/', views.add_item, name='add_item'),
    path('add_production_line/', views.add_production_line, name='add_production_line'),
    path('get_production_line/', views.get_production_line, name='get_production_line'),
    path('delete_production_line/', views.delete_production_line, name='delete_production_line'),
    path('user_list/', views.user_list, name='user_list'),
    path('item_list/', item_list, name='item_list'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('get_item_code/', views.get_item_code, name='get_item_code'),
    path('get_line_numbers/', views.get_line_numbers, name='get_line_numbers'),
    path('create_production_order/', views.create_production_order, name='create_production_order'),
    path('get_item_name/<int:item_id>/', views.get_item_name, name='get_item_name'),
    path('get_production_order_list/', views.get_production_order_list, name='get_production_order_list'),
    path('update_production_order/', views.update_production_order, name='update_production_order'),
    path('add_tolerance/', views.add_tolerance, name='add_tolerance'),
    path('get_tolerance_list/', views.get_tolerance_list, name='get_tolerance_list'),
    path('update_tolerance/', views.update_tolerance, name='update_tolerance'),
    path('add_mould/', views.add_mould, name='add_mould'),
    path('get_mould_list/', views.get_mould_list, name='get_mould_list'),
    path('update_mould/', views.update_mould, name='update_mould'),
    path('get_production_order_numbers_by_line/', views.get_production_order_numbers_by_line, name='get_production_order_numbers_by_line'),
    path('get_product_details_by_order/<str:production_order_no>/', views.get_product_details_by_order, name='get_product_details_by_order'),
    path('generate_prn/', views.generate_prn, name='generate_prn'),
    path('get_weight/', views.get_weight, name='get_weight'),
    path('get_batch_data/', views.get_batch_data, name='get_batch_data'),
    path('reprint_label/', views.reprint_label, name='reprint_label'),
    path('add_printer/', views.add_printer, name='add_printer'),
    path('get_printer_list/', views.get_printer_list, name='get_printer_list'),
    path('get_production_lines/', views.get_production_lines, name='get_production_lines'),
    path('update_printer/', views.update_printer, name='update_printer'),
    path('delete_printer/', views.delete_printer, name='delete_printer'),
    path('quality_control/', views.quality_control, name='quality_control'),
    path('approve_qc/', views.approve_qc, name='approve_qc'),
    path('reject_qc/', views.reject_qc, name='reject_qc'),
    path('get_batch_data_for_qc/', views.get_batch_data_for_qc, name='get_batch_data_for_qc'),
    path('generate_carton/', views.generate_carton, name='generate_carton'),
    path('get_single_carton_list/', views.get_single_carton_list, name='get_single_carton_list'),
    path('check_polybag_status/', views.check_polybag_status, name='check_polybag_status'),
    path('short_closure/', views.short_closure, name='short_closure'),
    path('get_production_order_numbers/', views.get_production_order_numbers, name='get_production_order_numbers'),
    path('get_po_details_for_sc/', views.get_po_details_for_sc, name='get_po_details_for_sc'),
    path('save_remark/', views.save_remark, name='save_remark'),
]

product_tracking/models.py
from django.db import models

# Create your models here.

product_tracking/views.py
import os
import re
import time
import json
import serial
import socket
import logging
from decimal import Decimal
from datetime import datetime
import serial.tools.list_ports
from django.urls import reverse
from django.db import connection
from psycopg2 import DatabaseError
from django.contrib import messages
from .decorators import check_module_access
from django.shortcuts import redirect, render
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.db import DatabaseError, OperationalError
from django.contrib.auth import logout
from django.views.decorators.http import require_POST

logger = logging.getLogger(__name__)
serial_number_counter = 1
serial_number = 1
serial_number_map = {}
prev_item_code = None
prev_batch = None


def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        line_number = request.POST.get('line_number')

        with connection.cursor() as cursor:
            cursor.execute("SELECT is_valid, user_id FROM public.validate_user(%s, %s, %s)", [username, password, True])
            result = cursor.fetchone()

            if result and result[0]:
                user_id = result[1]
                cursor.execute(
                    "SELECT mm.module_name FROM user_junction_master ujm JOIN module_master mm ON ujm.module_id = mm.module_id WHERE ujm.user_id = %s",
                    [user_id])
                modules = cursor.fetchall()

                # Store user info and modules in session
                request.session['username'] = username
                request.session['user_id'] = user_id
                request.session['line_number'] = line_number
                request.session['modules'] = [module[0] for module in modules]

                if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                    return JsonResponse({'status': 'success', 'redirect_url': reverse('product_tracking:index')})
                else:
                    return redirect(reverse('product_tracking:index'))
            else:
                messages.error(request, "Invalid login details")
                return render(request, 'product_tracking/auth-signin.html', {'line_list': get_line_list()})

    return render(request, 'product_tracking/auth-signin.html', {'line_list': get_line_list()})


def get_line_list():
    """Utility function to fetch line list."""
    with connection.cursor() as cursor:
        cursor.execute("SELECT pl_id, line_no FROM pl_master")
        lines = cursor.fetchall()
        return [{'pl_id': line[0], 'line_no': line[1]} for line in lines]


def index_view(request):
    # Retrieve session data
    username = request.session.get('username', 'N/A')
    line_number = request.session.get('line_number', 'N/A')
    user_id = request.session.get('user_id', None)  # Retrieve the user_id to check if it's correctly stored
    modules = request.session.get('modules', None)

    # Log the retrieved session data
    print(f"Accessing index view")
    print(f"Session Data - Username: {username}, Line Number: {line_number}, User ID: {user_id}, Modules:{modules}")

    if not username or username == 'N/A':
        print("No username in session; redirecting to login")
        return redirect('product_tracking:login_view')

    # If session data is valid, render the index page with the session data
    return render(request, 'product_tracking/index.html', {
        'username': username,
        'line_number': line_number,
        'user_id': user_id  # Optionally pass user_id to the template if needed
    })


def production_order(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.user.username
    return render(request, 'product_tracking/production-order.html', {'username': username, 'line_number': line_number})


def label_printing(request):
    username = request.user.username
    line_number = request.session.get('line_number', 'N/A')  # Get the line number from session
    return render(request, 'product_tracking/label-printing.html', {'username': username, 'line_number': line_number})


def label_reprinting(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.user.username
    return render(request, 'product_tracking/label-reprinting.html', {'username': username, 'line_number': line_number})


def stock_verification(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.user.username
    return render(request, 'product_tracking/stock-verification-request.html',
                  {'username': username, 'line_number': line_number})


def stock_approval(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.user.username
    return render(request, 'product_tracking/stock-approval.html', {'username': username, 'line_number': line_number})


def user_logout(request):
    logout(request)
    return redirect(reverse('product_tracking:login_view'))  # Corrected from 'login' to 'login_view'


def add_user(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.session.get('username', 'N/A')
    user_id = request.session.get('user_id', None)

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        status = request.POST.get('status', '1')  # If status is not provided, default to '1' (active)
        modules = request.POST.getlist('modules')

        # Password validation
        if not is_valid_password(password):
            error_message = 'Password must be at least 8 characters long, alphanumeric, and contain at least one special character.'
            return render(request, 'product_tracking/user-master.html',
                          {'username': username, 'line_number': line_number, 'error_message': error_message})

        created_date = datetime.now()

        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT add_user_and_modules(%s, %s, %s, %s, %s, %s);",
                [username, password, status, modules, user_id, created_date])
            user_id = cursor.fetchone()[0]
        return JsonResponse({'message': 'User Added successfully'}, status=200)

    else:
        return render(request, 'product_tracking/user-master.html', {'username': username, 'line_number': line_number})


def is_valid_password(password):
    # Password should be at least 8 characters long, alphanumeric, and contain at least one special character
    if len(password) < 8:
        return False

    # Check for alphanumeric and special character
    if not re.match(r'^(?=.*[a-zA-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$', password):
        return False

    return True


def add_production_line(request):
    line_number = request.session.get('line_number', 'N/A')
    username = request.session.get('username', 'N/A')
    created_by = request.session.get('user_id')

    if not created_by:
        return JsonResponse({'success': False, 'message': 'Session expired, please log in again.'}, status=403)

    if request.method == 'POST':
        line_no = request.POST.get('line_no').strip()  # Clean input
        created_date = datetime.now()

        # Ensure created_by is an integer
        try:
            created_by = int(created_by)  # Convert to int, might raise ValueError if not possible
        except ValueError:
            return JsonResponse({'success': False, 'message': 'Invalid user ID'}, status=400)

        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM pl_master WHERE line_no = %s", [line_no])
            line_count = cursor.fetchone()[0]

            if line_count > 0:
                return JsonResponse({'success': False, 'message': 'Line already exists!'})

            try:
                cursor.execute(
                    "SELECT add_product_line(%s, %s, %s);",
                    [line_no, created_by, created_date])
                cursor.fetchone()  # Assuming function returns something
                return JsonResponse({'success': True, 'message': 'Production line added successfully'})
            except Exception as e:
                print("An unexpected error occurred:", e)
                return JsonResponse({'success': False, 'message': str(e)}, status=500)
    else:
        # Return the page with the form initially
        return render(request, 'product_tracking/production-line.html',
                      {'username': username, 'line_number': line_number})


def get_production_line(request):
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM get_pl()")
            rows = cursor.fetchall()
            production_lines = []
            for row in rows:
                production_lines.append({
                    'line_no': row[0],
                    'created_by': row[1],
                    'created_date': row[2].strftime('%d-%m-%Y'),
                    'user_name': row[3]
                })
        return JsonResponse({'success': True, 'production_lines': production_lines})
    except Exception as e:
        print("An unexpected error occurred:", e)
        return JsonResponse({'success': False, 'message': 'An unexpected error occurred'})


def delete_production_line(request):
    if request.method == 'POST':
        line_no = request.POST.get('line_no')
        try:
            with connection.cursor() as cursor:
                cursor.callproc('delete_pl', [line_no])
                return JsonResponse({'success': True, 'message': 'Production Line deleted successfully!'})
        except Exception as e:
            print("An unexpected error occurred:", e)
            return JsonResponse(
                {'success': False, 'message': 'An unexpected error occurred while deleting the production line.'})

product_tracking/templates/product_tracking/footer.html
{% load static %}
 <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Tekvan.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Tekvan IT Solutions
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

 <!-- JAVASCRIPT -->
      <script src="{% static 'product_tracking/assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'product_tracking/assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'product_tracking/assets/js/plugins.js' %}"></script>

    <!-- apexcharts -->
    <script src="{% static 'product_tracking/assets/libs/apexcharts/apexcharts.min.js' %}"></script>

    <script src="{% static 'product_tracking/assets/libs/list.js/list.min.js' %}"></script>

    <!-- Dashboard init -->
    <script src="{% static 'product_tracking/assets/js/pages/dashboard-analytics.init.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'product_tracking/assets/js/app.js' %}"></script>

    <script src="{% static 'product_tracking/assets/js/pages/datatables.init.js'%}"></script>

    <script src="{% static 'product_tracking/assets/libs/flatpickr/flatpickr.min.js'%}"></script>

product_tracking/templates/product_tracking/head.html
{% load static %}
        <meta charset="utf-8">
        <title> WMS </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="" name="description">
        <meta content="" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'product_tracking/assets/images/favicon.ico' %}">

        <!-- Layout config Js -->
        <script src="{% static 'product_tracking/assets/js/layout.js' %}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'product_tracking/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'product_tracking/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'product_tracking/assets/css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'product_tracking/assets/css/custom.min.css' %}" rel="stylesheet" type="text/css">

product_tracking/templates/product_tracking/short_closure.html
{% include 'product_tracking/head.html' %}
{% load static %}
{% block content %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            // Fetch and populate PO numbers
            $.ajax({
                url: "{% url 'product_tracking:get_production_order_numbers' %}",
                type: "GET",
                success: function (response) {
                    var productionOrderDropdown = $('#production-order-number');
                    productionOrderDropdown.empty();
                    productionOrderDropdown.append('<option value="">Select PO</option>');
                    $.each(response.production_order_numbers, function (index, value) {
                        productionOrderDropdown.append('<option value="' + value + '">' + value + '</option>');
                    });
                },
                error: function (error) {
                    console.log("Error fetching production order numbers:", error);
                }
            });

            // Fetch and display PO details on selection
            $('#production-order-number').change(function () {
                var selectedPONumber = $(this).val();
                if (selectedPONumber) {
                    $.ajax({
                        url: "{% url 'product_tracking:get_po_details_for_sc' %}",
                        type: "GET",
                        data: {
                            'production_order_number': selectedPONumber
                        },
                        success: function (response) {
                            $('#selected-po-number').text(selectedPONumber);
                            $('#total-polybag').text(response.total_polybags);
                            $('#printed-polybag').text(response.no_of_labels);
                            $('#remaining-polybag').text(response.remaining_labels);
                        },
                        error: function (error) {
                            console.log("Error fetching PO details:", error);
                        }
                    });
                } else {
                    $('#selected-po-number').text('');
                    $('#total-polybag').text('');
                    $('#printed-polybag').text('');
                    $('#remaining-polybag').text('');
                }
            });

            // Show the modal on button click
            $('#short-closure-btn').click(function () {
                $('#remarkModal').modal('show');
            });

            // Handle the form submission
            $('#remark-form').submit(function (e) {
                e.preventDefault();
                var remark = $('#remark').val();
                var selectedPONumber = $('#production-order-number').val();

                $.ajax({
                    url: "{% url 'product_tracking:save_remark' %}",
                    type: "POST",
                    data: {
                        'remark': remark,
                        'production_order_number': selectedPONumber,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        if (response.success) {
                            // Handle success
                            $('#remarkModal').modal('hide');
                            location.reload();
                        } else {
                            alert("Error saving remark.");
                        }
                    },
                    error: function (error) {
                        console.log("Error submitting remark:", error);
                    }
                });
            });
            $('#cancelButton').on('click', function () {
                $('#remarkModal').modal('hide');
                $('#remark').val('');
            });
        });
    </script>
    <body>

    <!-- Begin page -->
    <div id="layout-wrapper">

        <!-- ========== App Menu ========== -->
        {% include 'product_tracking/menu.html' %}

        <div class="sidebar-background"></div>
    </div>
    <!-- Left Sidebar End -->
    <!-- Vertical Overlay-->
    <div class="vertical-overlay"></div>
    {% include 'product_tracking/header.html' %}
    <div class="wrapper"></div>

    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0">short Closure</h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">Production</a>
                                    </li>
                                    <li class="breadcrumb-item active">Short Closure</li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title mb-0">Short Closure</h4>
                            </div><!-- end card header -->
                            <div class="card-body">
                                <form method="POST" action="{% url 'product_tracking:short_closure' %}" id="add-form">
                                    {% csrf_token %}
                                    <div class="row g-3">
                                        <div class="col-lg-4">
                                            <div class="form-floating" style="margin-top: 10px;">
                                                <select name="production_order_number" class="form-control"
                                                        id="production-order-number" required>
                                                    <option value="">Select PO</option>
                                                </select>
                                                <label for="production-order-number">PO Number</label>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                                <div class="text-center mt-3">
                                    <button id="short-closure-btn" class="btn btn-primary" style="margin-right: 900px;">
                                        Short Closure
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">Production Order Details</h5>
                            </div>
                            <div class="card-body">
                                <table id="example"
                                       class="table table-bordered dt-responsive nowrap table-striped align-middle"
                                       style="width:100%">
                                    <thead style="background: rgba(155,198,221,0.58)">
                                    <tr>
                                        <th>PO Number</th>
                                        <th>Total Polybags</th>
                                        <th>Printed Polybags</th>
                                        <th>Remaining Polybags</th>
                                    </tr>
                                    </thead>
                                    <tbody id="category-table-body">
                                    <tr>
                                        <td id="selected-po-number"></td>
                                        <td id="total-polybag"></td>
                                        <td id="printed-polybag"></td>
                                        <td id="remaining-polybag"></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!--end col-->

                <!-- Modal -->
                <div class="modal fade" id="remarkModal" tabindex="-1" role="dialog" aria-labelledby="remarkModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="remarkModalLabel">Add SC Remark</h5>
                            </div>
                            <div class="modal-body">
                                <form id="remark-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="remark">Remark</label>
                                        <input type="text" class="form-control" id="remark" name="remark" required>
                                    </div>
                                    <div style="margin-top: 20px;">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal"
                                                id="cancelButton" style="margin-left: 10px;">Cancel
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--end row-->
        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->


    {% include 'product_tracking/footer.html' %}
    </div>
    <!-- end main content-->

    <!-- END layout-wrapper -->
    </body>
{% endblock %}